version: 0.0
os: linux
files:
  - source: /
    destination: /home/king-haki/app
permissions:
  - object: /home/king-haki/app
    owner: root
    group: root
hooks:
  BeforeInstall:
    - location: start-containers.sh
      timeout: 1000
      runas: root
  ApplicationStop:
    - location: stop-containers.sh
      timeout: 300
      runas: root