version: 0.0
os: linux

files:
  - source: /
    destination: /app/course_management_system
file_exists_behavior: OVERWRITE

hooks:
  BeforeInstall:
    - location: server_clear.sh
      runas: root
    - location: server_stop.sh
      runas: root
  AfterInstall:
    - location: fix_privileges.sh
      runas: root
  ApplicationStart:
    - location: server_start.sh
      runas: root
  ApplicationStop:
    - location: server_stop.sh
      runas: root
  ValidateService:
    - location: health_check.sh
      runas: root
      timeout: 1000
