version: 0.0
os: linux
files:
  - source: /
    destination: /app/courseManagementSystem
file_exists_behavior: OVERWRITE
permissions:
  - object: /app/courseManagementSystem
    owner: root
    group: root
hooks:
  BeforeInstall:
    - location: aws/before-install-pull-postgres.sh
      runas: root
  AfterInstall:
    - location: aws/after-install-start-db-container.sh
      runas: root
    - location: aws/after-install-start-gradle-spring-app.sh
      runas: root
    - location: aws/after-install-set-execute-permissions-for-jar.sh
      runas: root
  ApplicationStart:
    - location: aws/application-start.sh
      runas: root
  ApplicationStop:
    - location: aws/application-stop-remove-docker-container.sh
      runas: root