version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: start-containers.sh
      timeout: 1000
      runas: root
  ApplicationStop:
    - location: stop-containers.sh
      timeout: 300
      runas: root