version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
      docker: 18
  build:
    commands:
      - ./gradlew clean build
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - build/libs/promotion-0.0.1-SNAPSHOT.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes
