version: "3.8"
services:

  db:
    image: postgres:12-alpine
    container_name: cms_db_build
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cms_db
    ports:
      - "5433:5432"
