version: "3.8"
services:

  db:
    container_name: cms_db
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cms_db
    ports:
      - "5434:5432"

  api:
    container_name: cms_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8881:8881"
    environment:
      SPRING_PROFILES_ACTIVE: container
    volumes:
      - .:/opt/promotion
      - ./gradle.cache/}:/root/.gradle
