version: "3.8"
services:

  db:
    image: postgres:14.1-alpine
    container_name: cms_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432

  liquibase:
    image: liquibase/liquibase
    container_name: cms_liquibase
    depends_on:
      - db
    volumes:
     - ${WORKSPACE}/liquibase/changelog.xml:/liquibase/changelog.xml
     - ${WORKSPACE}/liquibase/changelogs:/liquibase/changelog
     - ${WORKSPACE}/liquibase/sql_scripts:/liquibase/sql_scripts
