version: "3.8"
services:

  db:
    image: postgres:12-alpine
    container_name: cms_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
