version: "3.8"
services:

  db:
    image: postgres:14.1-alpine
    container_name: cms_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cms_app
    depends_on:
      - db
    ports:
      - "8085:8881"


