version: "3.8"
services:

  db:
    image: postgres:14.1-alpine
    container_name: cms_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  app:
    image: zakhar0kostyshyn/cms_app
    container_name: cms_app
    depends_on:
      - db
    ports:
      - "8882:8080"


