spring:
  datasource:
    url: jdbc:postgresql://cms_db:5432/cms_db
    username: root
    password: root
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: false
springdoc:
  swagger-ui:
    path: /swagger
security:
  secret: secret
app:
  minimum-course-pass-mark: 80
  max-course-for-student: 5
  minimum-lessons-per-course: 5
  controller-advise:
    generic-error-message: Something went wrong!
    show-stacktrace: true
