spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cms_db
    username: root
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    show-sql: true
server:
  port: 8188
springdoc:
  swagger-ui:
    path: /swagger-ui.html