spring:
  datasource:
    url: jdbc:postgresql://192.168.192.2:54321/cms_db
    username: root
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    show-sql: true
server:
  port: 8881
