spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DB}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
server:
  port: ${SPRING_SERVER_PORT}
springdoc:
  swagger-ui:
    path: ${SWAGGER_URL}