spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/cms_db
    username: root
    password: root
    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: liquibase/main_changelog.xml
    url: jdbc:postgresql://127.0.0.1:5432/cms_db
    password: root
    user: root
server:
  port: 8882
springdoc:
  swagger-ui:
    path: /swagger
security:
  secret: secret
app:
  minimum-course-pass-mark: 80
  max-course-for-student: 5
  minimum-lessons-per-course: 5
  controller-advise:
    generic-error-message: Something went wrong!
    show-stacktrace: true
