spring:
  datasource:
    url: jdbc:postgresql://cms_db:5432/cms_db
    username: root
    password: root
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: false
server:
  port: 8883
springdoc:
  swagger-ui:
    path: /swagger
security:
  secret: secret
