spring:
  datasource:
    url: jdbc:postgresql://cms_db:5432/cms_db
    username: root
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    show-sql: true
server:
  port: 8080
